# Generated by Django 6.0.5 on 2026-05-14 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alcancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_objetivo', models.DateField(blank=True, null=True)),
                ('monto_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_objetivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=7)),
                ('destino', models.CharField(blank=True, choices=[('billetera', 'Billetera'), ('alcancia', 'Alcancia')], max_length=10, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('alcancia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ahorros.alcancia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SafeBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billetera', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='alcancia',
            name='safe_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahorros.safebox'),
        ),
    ]
